// This file is auto-generated by @hey-api/openapi-ts

export const $artworks = {
    properties: {
        id: {
            description: `Note:
This is a Primary Key.<pk/>`,
            format: 'uuid',
            type: 'string'
        },
        name: {
            format: 'text',
            type: 'string'
        },
        description: {
            format: 'text',
            type: 'string'
        },
        slug: {
            format: 'text',
            type: 'string'
        },
        name_in_native_language: {
            format: 'text',
            type: 'string'
        },
        date_format: {
            format: 'text',
            type: 'string'
        },
        currency: {
            format: 'text',
            type: 'string'
        },
        is_published: {
            format: 'boolean',
            type: 'boolean'
        },
        file: {
            format: 'text',
            type: 'string'
        }
    },
    type: 'object'
} as const;