// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class IntrospectionService {
    /**
     * OpenAPI description (this document)
     * @returns unknown OK
     * @throws ApiError
     */
    public static get(): CancelablePromise<$OpenApiTs['/']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
    
}

export class RpcLoginService {
    /**
     * @param data The data for the request.
     * @param data.email
     * @param data.pass
     * @returns unknown OK
     * @throws ApiError
     */
    public static getRpcLogin(data: $OpenApiTs['/rpc/login']['get']['req']): CancelablePromise<$OpenApiTs['/rpc/login']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/rpc/login',
            query: {
                email: data.email,
                pass: data.pass
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.args
     * @param data.prefer Preference
     * @returns unknown OK
     * @throws ApiError
     */
    public static postRpcLogin(data: $OpenApiTs['/rpc/login']['post']['req']): CancelablePromise<$OpenApiTs['/rpc/login']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/rpc/login',
            headers: {
                Prefer: data.prefer
            },
            body: data.args
        });
    }
    
}

export class RpcRegisterPersonService {
    /**
     * @param data The data for the request.
     * @param data.firstname
     * @param data.lastname
     * @param data.email
     * @param data.password
     * @returns unknown OK
     * @throws ApiError
     */
    public static getRpcRegisterPerson(data: $OpenApiTs['/rpc/register_person']['get']['req']): CancelablePromise<$OpenApiTs['/rpc/register_person']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/rpc/register_person',
            query: {
                firstname: data.firstname,
                lastname: data.lastname,
                email: data.email,
                password: data.password
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.args
     * @param data.prefer Preference
     * @returns unknown OK
     * @throws ApiError
     */
    public static postRpcRegisterPerson(data: $OpenApiTs['/rpc/register_person']['post']['req']): CancelablePromise<$OpenApiTs['/rpc/register_person']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/rpc/register_person',
            headers: {
                Prefer: data.prefer
            },
            body: data.args
        });
    }
    
}