// This file is auto-generated by @hey-api/openapi-ts

export type artworks = {
  /**
   * Note:
   * This is a Primary Key.<pk/>
   */
  id?: string;
  name?: string;
  description?: string;
  slug?: string;
  name_in_native_language?: string;
  date_format?: string;
  currency?: string;
  is_published?: boolean;
  file?: string;
};

export type $OpenApiTs = {
  "/": {
    get: {
      res: {
        /**
         * OK
         */
        200: unknown;
      };
    };
  };
  "/artworks": {
    get: {
      req: {
        currency?: string;
        dateFormat?: string;
        description?: string;
        file?: string;
        id?: string;
        isPublished?: string;
        /**
         * Limiting and Pagination
         */
        limit?: string;
        name?: string;
        nameInNativeLanguage?: string;
        /**
         * Limiting and Pagination
         */
        offset?: string;
        /**
         * Ordering
         */
        order?: string;
        /**
         * Preference
         */
        prefer?: "count=none";
        /**
         * Limiting and Pagination
         */
        range?: string;
        /**
         * Limiting and Pagination
         */
        rangeUnit?: string;
        /**
         * Filtering Columns
         */
        select?: string;
        slug?: string;
      };
      res: {
        /**
         * OK
         */
        200: Array<artworks>;
        /**
         * Partial Content
         */
        206: unknown;
      };
    };
    post: {
      req: {
        /**
         * artworks
         */
        artworks?: artworks;
        /**
         * Preference
         */
        prefer?:
          | "return=representation"
          | "return=minimal"
          | "return=none"
          | "resolution=ignore-duplicates"
          | "resolution=merge-duplicates";
        /**
         * Filtering Columns
         */
        select?: string;
      };
      res: {
        /**
         * Created
         */
        201: unknown;
      };
    };
    delete: {
      req: {
        currency?: string;
        dateFormat?: string;
        description?: string;
        file?: string;
        id?: string;
        isPublished?: string;
        name?: string;
        nameInNativeLanguage?: string;
        /**
         * Preference
         */
        prefer?: "return=representation" | "return=minimal" | "return=none";
        slug?: string;
      };
      res: {
        /**
         * No Content
         */
        204: void;
      };
    };
    patch: {
      req: {
        /**
         * artworks
         */
        artworks?: artworks;
        currency?: string;
        dateFormat?: string;
        description?: string;
        file?: string;
        id?: string;
        isPublished?: string;
        name?: string;
        nameInNativeLanguage?: string;
        /**
         * Preference
         */
        prefer?: "return=representation" | "return=minimal" | "return=none";
        slug?: string;
      };
      res: {
        /**
         * No Content
         */
        204: void;
      };
    };
  };
};

