// This file is auto-generated by @hey-api/openapi-ts

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/rpc/login': {
        get: {
            req: {
                email: string;
                pass: string;
            };
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        post: {
            req: {
                args: {
                    email: string;
                    pass: string;
                };
                /**
                 * Preference
                 */
                prefer?: 'params=single-object';
            };
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/rpc/register_person': {
        get: {
            req: {
                email: string;
                firstname: string;
                lastname: string;
                password: string;
            };
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        post: {
            req: {
                args: {
                    email: string;
                    firstname: string;
                    lastname: string;
                    password: string;
                };
                /**
                 * Preference
                 */
                prefer?: 'params=single-object';
            };
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
};