// This file is auto-generated by @hey-api/openapi-ts

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
};